In [2]:
import pandas as pd
import numpy as np

# Load the dataset
dataset = pd.read_csv("C:\\Users\\HP\\Downloads\\large_employee_attrition_dataset.csv")
dataset

,EmployeeID,Age,Gender,Department,JobRole,Tenure,PerformanceRating,SatisfactionScore,WorkLifeBalance,Salary,AttritionStatus,ReasonForAttrition,JobDept_Interaction,HighRisk
0,-1.730320,0.640905,-0.926680,0.847310,1.326558,0.940490,1.248849,-1.450979,-1.211377,-0.146096,1.484967,3.057539,2.173867,Yes
1,-1.706071,0.552553,-0.926680,0.258491,-0.281781,-1.389463,-1.183184,-0.439844,-1.211377,-0.950303,1.484967,0.236931,-0.023290,Yes
2,-1.699143,-1.214486,-0.926680,1.436128,-0.281781,-1.165097,0.032832,-1.450979,0.012236,-1.030561,1.484967,0.942083,1.154347,Yes
3,-1.688750,0.375849,-0.926680,-0.919146,-1.246784,0.992266,0.032832,0.795988,1.235850,-0.401968,1.484967,-0.468221,-2.165930,Yes
4,-1.681822,-1.037782,-0.926680,1.436128,-0.281781,0.836936,-1.183184,-0.889237,-1.211377,1.535577,1.484967,0.942083,1.154347,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,1.674894,0.464201,1.079121,0.258491,1.004890,-1.527534,1.248849,1.582427,1.235850,0.616715,1.484967,-0.468221,1.263381,Yes
308,1.681822,-1.126134,-0.926680,1.436128,-0.281781,1.044043,0.032832,-0.327495,0.012236,1.707293,1.484967,-0.468221,1.154347,Yes
309,1.702607,-0.330966,-0.926680,-0.919146,-1.246784,1.078561,0.032832,0.121898,0.012236,0.131913,1.484967,-0.468221,-2.165930,Yes
310,1.719927,-0.772726,1.079121,-0.330327,1.648226,-1.113320,-1.183184,0.795988,1.235850,-0.931156,1.484967,-0.468221,1.317898,Yes
311,1.723391,-1.391190,1.079121,0.258491,1.004890,-1.303168,1.248849,-1.113934,1.235850,-0.888511,1.484967,-0.468221,1.263381,Yes

In [ ]:
import dash
from dash import dcc, html
import pandas as pd
import plotly.express as px
from dash.dependencies import Input, Output

# Load your data
dataset = pd.read_csv("C:\\Users\\HP\\Downloads\\large_employee_attrition_dataset.csv")

# Initialize the Dash app
app = dash.Dash(__name__)

# Layout of the dashboard
app.layout = html.Div([
    html.H1("Employee Attrition Dashboard"),

    # Age range slider
    dcc.RangeSlider(
        id='age-slider',
        min=dataset['Age'].min(),
        max=dataset['Age'].max(),
        step=1,
        marks={i: str(i) for i in range(int(dataset['Age'].min()), int(dataset['Age'].max()) + 1, 5)},
        value=[25, 45]
    ),

    # Graphs for attrition and other metrics
    dcc.Graph(id='attrition-pie-chart'),
])

# Callback function to update the graphs based on the slider input
@app.callback(
    Output('attrition-pie-chart', 'figure'),
    [Input('age-slider', 'value')]
)
def update_graph(age_range):
    # Filter data based on the age range
    filtered_dataset = dataset[(dataset['Age'] >= age_range[0]) & (dataset['Age'] <= age_range[1])]

    # Create the pie chart for attrition
    attritionstatus_pie = px.pie(filtered_dataset, names='AttritionStatus', title='Employee Attrition')
    return attritionstatus_pie

# Run the app
if __name__ == '__main__':
    app.run_server(debug=True)

In [ ]:
'http://127.0.0.1:8050'